### ISSUE TITLE
[FEATURE] slug functionality is missing for v9 routing

### ISSUE THREAD

**Issue by mgrundkoetter** [mittwald/typo3_forum#268]
There need to be some `slug` fields in the db tables, the corresponding TCA an an example of a route config yaml in the docs. I'm working on a PR.

**Comment by mgrundkoetter** [comment]
Routing with default values (for widget:paginate) does not work right not, see https://forge.typo3.org/issues/87436 and https://forge.typo3.org/issues/86895

So my current config does not work for that reason as well.

```yaml
routeEnhancers:
  Forum:
    type: Extbase
    extension: Typo3Forum
    plugin: Pi1
    routes:
      -
        routePath: '/{forum_alias}/{page}'
        _controller: 'Forum::show'
        _arguments:
          forum_alias: forum
          page: '@widget_0/currentPage'
      -
        routePath: '/{forum_alias}/{topic_alias}/{page}'
        _controller: 'Topic::show'
        _arguments:
          topic_alias: topic
          forum_alias: forum
          page: '@widget_0/currentPage'
      -
        routePath: '/beitrag/{post_id}/melden'
        _controller: 'Report::newPostReport'
        _arguments:
          post_id: post
    defaultController: 'Forum::show'
    defaults:
      page: '1'
    requirements:
      page: '\d+'
      forum_alias: '^[a-Z0-9]+$'
      topic_alias: '^[a-Z0-9]+$'
      post_id: '\d+'
    aspects:
      forum_alias:
        type: PersistedAliasMapper
        tableName: tx_typo3forum_domain_model_forum_forum
        routeFieldName: slug
      topic_alias:
        type: PersistedAliasMapper
        tableName: tx_typo3forum_domain_model_forum_topic
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '999'
      post_id:
        type: PersistedAliasMapper
        tableName: tx_typo3forum_domain_model_forum_post
        routeFieldName: uid
```

Also, for this very routing, all the calls to `Topic::show`(by `f:link.action`) need to be adjusted in the templates. The parameter `forum: topic.forum` needs to be added.
